# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 209cd8a6c9170f6b68a8609940b3be1df91dd2d61e6af21a4d9c01e39b510d9880ac306c5968eec514b8cd7cbe86758ddbe6f6941db8e0db685822ad17c163ed

test:
  secret_key_base: 6a64ad4bf8a987474742adf16ce2fb31a30d7c909ec01dce86db6a842f64d345a65d6e067d4b19b21b9f015a0c8b85b5faf503460a8e97cb6b5572a686313b85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
